# Neural Network using numpy

![Neural Network](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fanalyticsindiamag.com%2Fwp-content%2Fuploads%2F2018%2F05%2Fnural-network_3.gif&f=1)

[Credits](https://analyticsindiamag.com/a-guide-to-switching-careers-to-deep-learning/)

In [1]:
import numpy as np

In [6]:
np.random.seed(99)

# Input X

In [5]:
x = np.array([[1 ,0 , 1 , 0] , [1 , 0 , 1 , 1] , [0 , 1 , 0 , 1]])
print(x)
print("Shape of x --> " , x.shape)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Shape of x -->  (3, 4)


# Output y

In [7]:
y = np.array([ [1] , [1] , [0]])
print(y)
print("Shape of y --> " , y.shape)

[[1]
 [1]
 [0]]
Shape of y -->  (3, 1)


# First Layer Weights  

In [9]:
wh = np.random.rand(4,3)
print(wh)
print("Shape of wh --> ", wh.shape)

[[0.37743894 0.49414745 0.92894839]
 [0.39545404 0.9739563  0.52441472]
 [0.09361309 0.81330841 0.21168679]
 [0.55434578 0.29226912 0.81614236]]
Shape of wh -->  (4, 3)


# First Layer Bias

In [10]:
bh = np.random.rand(1,3)
print(bh)
print("Shape of bh --> " ,bh.shape)

[[0.82804257 0.22157737 0.6448347 ]]
Shape of bh -->  (1, 3)


# Hidden Layer Input
---
Dot product of input matrix x and weights results in hidden layer input matrix.

In [11]:
hidden_layer_output = np.dot(x , wh) + bh
print(hidden_layer_output)
print("Hidden Layer input shape --> " , hidden_layer_output.shape)

[[1.2990946  1.52903324 1.78546988]
 [1.85344038 1.82130235 2.60161224]
 [1.7778424  1.48780278 1.98539178]]
Hidden Layer input shape -->  (3, 3)


# Sigmoid Activation Function
---

![Sigmoid Activation FUnction](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F1600%2F1*Xu7B5y9gp0iL5ooBj7LtWw.png&f=1) 
[Image credits SAGAR SHARMA](https://bit.ly/2ntXyn8)

In [18]:
from math import exp 
def sigmoid(x_value):
  
  return (1/(1+exp(-x_value)))

# Hidden Layer activations

In [19]:
sig_vect = np.vectorize(sigmoid)
hidden_layer_activations = sig_vect(hidden_layer_output)

# Hidden Layer Weights

In [20]:
wout = np.random.rand(3 , 1)
print(wout)
print("Shape of wout -->" , wout.shape)

[[0.23504378]
 [0.006553  ]
 [0.89864419]]
Shape of wout --> (3, 1)


# Hidden Layer Bias

In [21]:
bout = np.random.rand(1)
print(bout)
print("Shape of bout -->" , bout.shape)

[0.55223443]
Shape of bout --> (1,)


# Input to Output Layer
---
Hidden layer output is the input to Output layer.Dot product of hidden layer activations and wout will result in Hidden layer output and summed with bias unit.

In [23]:
output_layer_input = np.dot(hidden_layer_activations , wout) + bout
print(output_layer_input)
print("Shape of output_layer_input -->" , output_layer_input.shape)

[[1.51186271]
 [1.5976838 ]
 [1.54878076]]
Shape of output_layer_input --> (3, 1)


# Output Layer output


In [24]:
output = sig_vect(output_layer_input)
print(output)
print("Shape of output --> " ,output.shape)

[[0.8193371 ]
 [0.83169441]
 [0.82473757]]
Shape of output -->  (3, 1)


# Output loss Calculation

In [26]:
E = y - output
print(E)
print("Shape of E -->" , E.shape)

[[ 0.1806629 ]
 [ 0.16830559]
 [-0.82473757]]
Shape of E --> (3, 1)


---
---
# Backpropagation
---
---


# Derivative of Sigmoid Function

In [28]:
def derivative_sigmoid(sig_value):
    
    return (sig_value*(1 - sig_value))
    

In [29]:
sigmoid_derivative = np.vectorize(derivative_sigmoid)

# Slope of Output Layer

In [31]:
Slope_output_layer = sigmoid_derivative(output)
print(Slope_output_layer)
print("Shape of Slope_output_layer --> " , Slope_output_layer.shape)

[[0.14802382]
 [0.13997882]
 [0.14454551]]
Shape of Slope_output_layer -->  (3, 1)


# Slope of Hidden Layer

In [33]:
Slope_hidden_layer = sigmoid_derivative(hidden_layer_activations)
print(Slope_hidden_layer)
print("Shape of Slope_hidden_layer -->" , Slope_hidden_layer.shape)

[[0.16838547 0.14640304 0.12299973]
 [0.11711749 0.1198794  0.06426894]
 [0.12366934 0.15030304 0.10616583]]
Shape of Slope_hidden_layer --> (3, 3)


In [34]:
lr = 0.01
d_output = E * Slope_output_layer * lr
print(d_output)


[[ 0.00026742]
 [ 0.00023559]
 [-0.00119212]]


In [35]:
print("Shape of d_output--> ", d_output.shape)
print("Shape of wout transpose --> " ,(np.transpose(wout)).shape )
Error_at_hidden_layer = np.dot(d_output , np.transpose(wout))
Error_at_hidden_layer

Shape of d_output-->  (3, 1)
Shape of wout transpose -->  (1, 3)


array([[ 6.28563790e-05,  1.75243105e-06,  2.40319141e-04],
       [ 5.53744732e-05,  1.54383608e-06,  2.11713529e-04],
       [-2.80200662e-04, -7.81197307e-06, -1.07129274e-03]])

In [38]:
d_hidden_layer = Error_at_hidden_layer * Slope_hidden_layer
d_hidden_layer

array([[ 1.48029510e-05,  4.31878703e-05,  6.80003971e-06],
       [ 1.19963075e-05,  2.20732520e-05,  2.79686274e-06],
       [-1.06220945e-04, -1.08508235e-04, -5.10882704e-05]])

# Update weights 

In [40]:
wout = wout + np.dot( np.transpose(hidden_layer_activations) , d_output) * lr
wout

array([[0.39545058],
       [0.97394962],
       [0.52440853]])

In [41]:
wh = wh + np.dot(np.transpose(x) , d_hidden_layer ) * lr
wh

array([[0.67227883, 0.48807905, 0.82549527],
       [0.03144533, 0.80804888, 0.56561691],
       [0.29762277, 0.04669637, 0.9906275 ],
       [0.00682479, 0.76979216, 0.74676662]])

# Update bias

In [53]:
bh = bh + np.sum(d_hidden_layer , axis = 0) * lr
bh

array([[0.37743814, 0.49414702, 0.92894798]])

In [54]:
bout = bout + np.sum(d_output , axis = 0) * lr
bout

array([0.09360602])